MESSAGE_TIMESPAN = 60000
SIMULATED_DATA = True
GPIO_PIN_ADDRESS = 24
BLINK_TIMESPAN = 1000
CONNECTION_STRING = 'HostName=PuIOThub.azure-devices.net;DeviceId=raspPI;SharedAccessKey=wy4PMOIWpUXgSqsqMgJjPVPBB0qMPaRg+45nvAZpu88='
